use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use serde_json::Value;
use sha2::{Digest, Sha256};

type DynResult<T> = Result<T, Box<dyn std::error::Error>>;

pub fn generate(
  registry_path: &Path,
  system_family_manifest_path: &Path,
  architecture_registry_path: &Path,
  output_path: &Path,
) -> DynResult<()> {
  let generated = render(registry_path, system_family_manifest_path, architecture_registry_path)?;
  if let Some(parent) = output_path.parent() {
    fs::create_dir_all(parent)?;
  }
  fs::write(output_path, generated)?;
  Ok(())
}

pub fn check(
  registry_path: &Path,
  system_family_manifest_path: &Path,
  architecture_registry_path: &Path,
  output_path: &Path,
) -> DynResult<()> {
  let expected = render(registry_path, system_family_manifest_path, architecture_registry_path)?;
  let actual = fs::read_to_string(output_path)?;
  if actual != expected {
    return Err(
      format!(
        "generated contract is stale: run aeordb-v4-reference generate-contracts {} {} {} {}",
        registry_path.display(),
        system_family_manifest_path.display(),
        architecture_registry_path.display(),
        output_path.display()
      )
      .into(),
    );
  }
  Ok(())
}

fn render(registry_path: &Path, system_family_manifest_path: &Path, architecture_registry_path: &Path) -> DynResult<String> {
  let registry_bytes = fs::read(registry_path)?;
  let registry: Value = serde_json::from_slice(&registry_bytes)?;
  let system_family_bytes = fs::read(system_family_manifest_path)?;
  let system_family: Value = serde_json::from_slice(&system_family_bytes)?;
  let architecture_bytes = fs::read(architecture_registry_path)?;
  let architecture: Value = serde_json::from_slice(&architecture_bytes)?;
  validate(&registry, &system_family)?;
  validate_architecture(&architecture)?;

  let source_sha256 = hex::encode(Sha256::digest(&registry_bytes));
  let source_blake3 = blake3::hash(&registry_bytes).to_hex().to_string();
  let system_family_sha256 = hex::encode(Sha256::digest(&system_family_bytes));
  let architecture_sha256 = hex::encode(Sha256::digest(&architecture_bytes));
  let mut output = String::new();
  output.push_str("// @generated by tools/v4-reference; do not edit by hand.\n");
  output.push_str("// Regenerate with `aeordb-v4-reference generate-contracts`.\n");
  output.push_str("#![allow(dead_code)]\n\n");
  output.push_str(&format!("pub const CONTRACT_REGISTRY_SHA256: &str = \"{source_sha256}\";\n"));
  output.push_str(&format!("pub const CONTRACT_REGISTRY_BLAKE3: &str = \"{source_blake3}\";\n"));
  output.push_str(&format!("pub const SYSTEM_FAMILY_MANIFEST_SHA256: &str = \"{system_family_sha256}\";\n\n"));
  output.push_str(&format!("pub const ARCHITECTURE_REGISTRY_SHA256: &str = \"{architecture_sha256}\";\n\n"));
  output.push_str(
    "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct RegistryValue { pub id: u16, pub name: &'static str }\n\n\
     #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct EntryTypeValue { pub id: u8, pub name: &'static str, pub kv_tag: u8 }\n\n\
     #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct KvTagValue { pub id: u8, pub name: &'static str, pub entry_type: Option<u8> }\n\n\
     #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct FormatLimit { pub id: &'static str, pub hard_cap: u64 }\n\n",
  );
  output.push_str(
    "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct ConfigProperty { pub id: u16, pub path: &'static str, pub environment: &'static str, pub cli: &'static str, pub kind: &'static str, pub activation: &'static str, pub owner: &'static str, pub lkg: bool, pub redaction: Option<&'static str> }\n\n\
     #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct DynamicRecordContract { pub id: u16, pub name: &'static str, pub discoverability: &'static str, pub retention_owner: &'static str }\n\n\
     #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct HardTransitionContract { pub id: u16, pub name: &'static str, pub selector: &'static str, pub crash_before: &'static str, pub crash_after: &'static str }\n\n\
     #[derive(Clone, Copy, Debug, PartialEq, Eq)]\n\
     pub struct CleanupResultContract { pub id: u16, pub name: &'static str, pub behavior: &'static str, pub debt_owner: &'static str }\n\n",
  );

  let capabilities = array_at(&registry, &["capability_bits"])?;
  render_registry_values(&mut output, "CAPABILITY_BITS", "capability_bit", capabilities, "bit")?;

  let entry_types = array_at(&registry, &["persistent_registries", "entry_type_v1"])?;
  output.push_str("pub const ENTRY_TYPES: &[EntryTypeValue] = &[\n");
  for row in entry_types {
    output.push_str(&format!(
      "  EntryTypeValue {{ id: {}, name: {:?}, kv_tag: {} }},\n",
      u64_field(row, "id")?,
      string_field(row, "name")?,
      u64_field(row, "kv_tag")?
    ));
  }
  output.push_str("];\n\npub mod entry_type {\n");
  render_numeric_constants(&mut output, entry_types, "id", "u8", 2)?;
  output.push_str("}\n\n");

  let kv_tags = array_at(&registry, &["persistent_registries", "kv_tag_v1"])?;
  output.push_str("pub const KV_TAGS: &[KvTagValue] = &[\n");
  for row in kv_tags {
    let entry_type = row.get("entry_type").ok_or("KV tag lacks entry_type")?;
    let entry_type = if entry_type.is_null() {
      "None".to_string()
    } else {
      format!("Some({})", entry_type.as_u64().ok_or("KV entry_type is not numeric")?)
    };
    output.push_str(&format!(
      "  KvTagValue {{ id: {}, name: {:?}, entry_type: {} }},\n",
      u64_field(row, "id")?,
      string_field(row, "name")?,
      entry_type
    ));
  }
  output.push_str("];\n\npub mod kv_tag {\n");
  render_numeric_constants(&mut output, kv_tags, "id", "u8", 2)?;
  output.push_str("}\n\n");

  let shared = object_at(&registry, &["persistent_registries", "shared_enums"])?;
  for (scope, values) in shared {
    let values = values.as_array().ok_or("shared enum scope is not an array")?;
    render_registry_values(&mut output, &rust_const(scope), scope, values, "id")?;
  }

  let formats = array_at(&registry, &["formats"])?;
  output.push_str("pub const FORMAT_LIMITS: &[FormatLimit] = &[\n");
  for format in formats {
    output.push_str(&format!("  FormatLimit {{ id: {:?}, hard_cap: {} }},\n", string_field(format, "id")?, u64_field(format, "hard_cap")?));
  }
  output.push_str("];\n\npub mod format_hard_cap {\n");
  for format in formats {
    output.push_str(&format!("  pub const {}: u64 = {};\n", rust_const(string_field(format, "id")?), u64_field(format, "hard_cap")?));
  }
  output.push_str("}\n\n");

  let source_rows = array_at(&system_family, &["source_rows"])?;
  output.push_str("pub const SYSTEM_FAMILIES: &[RegistryValue] = &[\n");
  for row in source_rows {
    output.push_str(&format!(
      "  RegistryValue {{ id: {}, name: {:?} }},\n",
      parse_hex_u16(string_field(row, "family_id")?)?,
      string_field(row, "label")?
    ));
  }
  output.push_str("];\n\npub mod system_family {\n");
  for row in source_rows {
    output.push_str(&format!(
      "  pub const {}: u16 = 0x{:04x};\n",
      rust_const(string_field(row, "label")?),
      parse_hex_u16(string_field(row, "family_id")?)?
    ));
  }
  output.push_str("  pub const UNKNOWN_PROTECTED: u16 = 0xfffe;\n}\n");

  let route_classes = array_at(&architecture, &["route_classes"])?;
  render_registry_values(&mut output, "ROUTE_CLASSES", "route_class", route_classes, "id")?;

  let config_properties = array_at(&architecture, &["configuration_properties"])?;
  output.push_str("pub const CONFIGURATION_PROPERTIES: &[ConfigProperty] = &[\n");
  for row in config_properties {
    let path = string_field(row, "path")?;
    output.push_str(&format!(
      "  ConfigProperty {{ id: {}, path: {:?}, environment: {:?}, cli: {:?}, kind: {:?}, activation: {:?}, owner: {:?}, lkg: {}, redaction: {} }},\n",
      u64_field(row, "id")?,
      path,
      environment_name(path),
      cli_name(path),
      string_field(row, "kind")?,
      string_field(row, "activation")?,
      string_field(row, "owner")?,
      bool_field(row, "lkg")?,
      optional_string_literal(row, "redaction")?
    ));
  }
  output.push_str("];\n\npub mod config_property_id {\n");
  for row in config_properties {
    output.push_str(&format!("  pub const {}: u16 = {};\n", rust_const(string_field(row, "path")?), u64_field(row, "id")?));
  }
  output.push_str("}\n\n");

  let dynamic_records = array_at(&architecture, &["dynamic_records"])?;
  output.push_str("pub const DYNAMIC_RECORDS: &[DynamicRecordContract] = &[\n");
  for row in dynamic_records {
    output.push_str(&format!(
      "  DynamicRecordContract {{ id: {}, name: {:?}, discoverability: {:?}, retention_owner: {:?} }},\n",
      u64_field(row, "id")?,
      string_field(row, "name")?,
      string_field(row, "discoverability")?,
      string_field(row, "retention_owner")?
    ));
  }
  output.push_str("];\n\n");

  let hard_transitions = array_at(&architecture, &["hard_transitions"])?;
  output.push_str("pub const HARD_TRANSITIONS: &[HardTransitionContract] = &[\n");
  for row in hard_transitions {
    output.push_str(&format!(
      "  HardTransitionContract {{ id: {}, name: {:?}, selector: {:?}, crash_before: {:?}, crash_after: {:?} }},\n",
      u64_field(row, "id")?,
      string_field(row, "name")?,
      string_field(row, "selector")?,
      string_field(row, "crash_before")?,
      string_field(row, "crash_after")?
    ));
  }
  output.push_str("];\n\n");

  let cleanup_results = array_at(&architecture, &["cleanup_result_classes"])?;
  output.push_str("pub const CLEANUP_RESULT_CLASSES: &[CleanupResultContract] = &[\n");
  for row in cleanup_results {
    output.push_str(&format!(
      "  CleanupResultContract {{ id: {}, name: {:?}, behavior: {:?}, debt_owner: {:?} }},\n",
      u64_field(row, "id")?,
      string_field(row, "name")?,
      string_field(row, "behavior")?,
      string_field(row, "debt_owner")?
    ));
  }
  output.push_str("];\n");
  Ok(output)
}

fn validate(registry: &Value, system_family: &Value) -> DynResult<()> {
  if u64_field(registry, "schema_version")? != 1 || string_field(registry, "campaign_id")? != "aeordb-v4-nvt-gc-2026-08-03" {
    return Err("contract registry identity mismatch".into());
  }
  let capabilities = array_at(registry, &["capability_bits"])?;
  validate_unique(capabilities, "bit", "name")?;
  let bits: Vec<_> = capabilities.iter().map(|row| u64_field(row, "bit")).collect::<Result<_, _>>()?;
  if bits != (0..24).collect::<Vec<_>>() {
    return Err("capability bits must be the exact contiguous 0..23 registry".into());
  }

  let entry_types = array_at(registry, &["persistent_registries", "entry_type_v1"])?;
  let kv_tags = array_at(registry, &["persistent_registries", "kv_tag_v1"])?;
  validate_unique(entry_types, "id", "name")?;
  validate_unique(kv_tags, "id", "name")?;
  for entry in entry_types {
    let entry_id = u64_field(entry, "id")?;
    let kv_tag = u64_field(entry, "kv_tag")?;
    let kv = kv_tags.iter().find(|row| u64_field(row, "id") == Ok(kv_tag)).ok_or("EntryType points to absent KV tag")?;
    if kv.get("entry_type").and_then(Value::as_u64) != Some(entry_id) {
      return Err("EntryType/KV tag mapping is not bidirectional".into());
    }
  }

  let shared = object_at(registry, &["persistent_registries", "shared_enums"])?;
  for (scope, rows) in shared {
    let rows = rows.as_array().ok_or("shared enum scope is not an array")?;
    validate_unique(rows, "id", "name")?;
    validate_rust_identifiers(scope, rows)?;
  }
  let formats = array_at(registry, &["formats"])?;
  validate_unique(formats, "id", "id")?;
  for format in formats {
    if u64_field(format, "hard_cap")? == 0
      || !nonempty_field(format, "identity")
      || string_field(format, "bounded_decode")?.is_empty()
      || array_at(format, &["fixture_ids_32"])?.is_empty()
      || array_at(format, &["fixture_ids_64"])?.is_empty()
    {
      return Err("format contract lacks bounded generation input".into());
    }
  }
  validate_rust_identifiers("format_hard_cap", formats)?;

  if u64_field(system_family, "source_row_count")? != 46 || u64_field(system_family, "descriptor_count")? != 61 {
    return Err("SystemFamily manifest count mismatch".into());
  }
  let families = array_at(system_family, &["source_rows"])?;
  validate_unique(families, "family_id", "label")?;
  validate_rust_identifiers("system_family", families)?;
  Ok(())
}

fn validate_architecture(architecture: &Value) -> DynResult<()> {
  if u64_field(architecture, "schema_version")? != 1
    || string_field(architecture, "campaign_id")? != "aeordb-v4-nvt-gc-2026-08-03"
    || string_field(architecture, "coverage_stage")? != "p0c-machine-contract"
  {
    return Err("architecture registry identity mismatch".into());
  }

  let route_classes = array_at(architecture, &["route_classes"])?;
  validate_exact_ids(route_classes, 7, "route class")?;
  validate_unique(route_classes, "id", "name")?;
  validate_rust_identifiers("route_class", route_classes)?;
  let expected_routes = [
    "single_root_namespace",
    "historical_aliases",
    "multi_root",
    "content_staging",
    "hash_retrieval",
    "operational_auth_system",
    "mutation",
  ];
  if route_classes.iter().map(|row| string_field(row, "name")).collect::<Result<Vec<_>, _>>()? != expected_routes {
    return Err("route class registry differs from the ratified seven classes".into());
  }
  for row in route_classes {
    require_nonempty_fields(row, &["selector", "authorization", "response_root"])?;
  }

  let properties = array_at(architecture, &["configuration_properties"])?;
  validate_exact_ids(properties, 41, "configuration property")?;
  validate_unique(properties, "id", "path")?;
  validate_rust_identifiers("configuration_property", properties)?;
  let mut environments = BTreeSet::new();
  let mut cli_names = BTreeSet::new();
  for row in properties {
    require_nonempty_fields(row, &["path", "kind", "default", "constraint", "activation", "owner"])?;
    bool_field(row, "lkg")?;
    if let Some(redaction) = row.get("redaction") {
      let redaction = redaction.as_str().ok_or("configuration redaction must be a string")?;
      if redaction != "root_only_path" {
        return Err(format!("unknown configuration redaction class: {redaction}").into());
      }
    }
    let activation = string_field(row, "activation")?;
    if !["startup_bound", "next_run_captured", "dynamically_staged"].contains(&activation) {
      return Err(format!("unknown configuration activation class: {activation}").into());
    }
    if !environments.insert(environment_name(string_field(row, "path")?)) || !cli_names.insert(cli_name(string_field(row, "path")?)) {
      return Err("generated configuration environment or CLI name collision".into());
    }
  }

  let dynamic_records = array_at(architecture, &["dynamic_records"])?;
  validate_contiguous_ids(dynamic_records, "dynamic record")?;
  validate_unique(dynamic_records, "id", "name")?;
  for row in dynamic_records {
    require_nonempty_fields(row, &["discoverability", "retention_owner"])?;
  }

  let transitions = array_at(architecture, &["hard_transitions"])?;
  validate_contiguous_ids(transitions, "hard transition")?;
  validate_unique(transitions, "id", "name")?;
  for row in transitions {
    require_nonempty_fields(row, &["selector", "crash_before", "crash_after"])?;
  }

  let cleanup = array_at(architecture, &["cleanup_result_classes"])?;
  validate_exact_ids(cleanup, 4, "cleanup result class")?;
  validate_unique(cleanup, "id", "name")?;
  for row in cleanup {
    require_nonempty_fields(row, &["behavior", "debt_owner"])?;
  }
  Ok(())
}

fn validate_exact_ids(rows: &[Value], expected: usize, scope: &str) -> DynResult<()> {
  if rows.len() != expected {
    return Err(format!("{scope} registry must contain exactly {expected} rows").into());
  }
  validate_contiguous_ids(rows, scope)
}

fn validate_contiguous_ids(rows: &[Value], scope: &str) -> DynResult<()> {
  let ids = rows.iter().map(|row| u64_field(row, "id")).collect::<Result<Vec<_>, _>>()?;
  if ids != (1..=rows.len() as u64).collect::<Vec<_>>() {
    return Err(format!("{scope} IDs must be contiguous and canonically ordered").into());
  }
  Ok(())
}

fn require_nonempty_fields(value: &Value, fields: &[&str]) -> DynResult<()> {
  for field in fields {
    if !nonempty_field(value, field) {
      return Err(format!("contract row lacks nonempty field: {field}").into());
    }
  }
  Ok(())
}

fn render_registry_values(output: &mut String, array_name: &str, module_name: &str, rows: &[Value], id_field: &str) -> DynResult<()> {
  output.push_str(&format!("pub const {}: &[RegistryValue] = &[\n", rust_const(array_name)));
  for row in rows {
    output.push_str(&format!("  RegistryValue {{ id: {}, name: {:?} }},\n", u64_field(row, id_field)?, string_field(row, "name")?));
  }
  output.push_str(&format!("];\n\npub mod {} {{\n", rust_module(module_name)));
  render_numeric_constants(output, rows, id_field, "u16", 2)?;
  output.push_str("}\n\n");
  Ok(())
}

fn render_numeric_constants(output: &mut String, rows: &[Value], id_field: &str, rust_type: &str, indent: usize) -> DynResult<()> {
  let prefix = " ".repeat(indent);
  for row in rows {
    output.push_str(&format!(
      "{}pub const {}: {} = {};\n",
      prefix,
      rust_const(string_field(row, "name")?),
      rust_type,
      u64_field(row, id_field)?
    ));
  }
  Ok(())
}

fn validate_unique(rows: &[Value], id_field: &str, name_field: &str) -> DynResult<()> {
  let mut ids = BTreeSet::new();
  let mut names = BTreeSet::new();
  for row in rows {
    let id = row.get(id_field).ok_or("registry row lacks ID")?;
    let id = if let Some(number) = id.as_u64() {
      format!("n:{number}")
    } else if let Some(text) = id.as_str() {
      format!("s:{text}")
    } else {
      return Err("registry ID has unsupported type".into());
    };
    let name = string_field(row, name_field)?;
    if !ids.insert(id) || !names.insert(name) {
      return Err("registry ID or name collision".into());
    }
  }
  Ok(())
}

fn validate_rust_identifiers(scope: &str, rows: &[Value]) -> DynResult<()> {
  let mut identifiers = BTreeSet::new();
  for row in rows {
    let name = ["name", "path", "id", "label"]
      .iter()
      .find_map(|field| row.get(*field).and_then(Value::as_str))
      .ok_or("row lacks identifier source")?;
    if !identifiers.insert(rust_const(name)) {
      return Err(format!("generated Rust identifier collision in {scope}").into());
    }
  }
  Ok(())
}

fn array_at<'a>(value: &'a Value, path: &[&str]) -> DynResult<&'a Vec<Value>> {
  let mut current = value;
  for segment in path {
    current = current.get(*segment).ok_or_else(|| format!("missing contract path: {}", path.join(".")))?;
  }
  current.as_array().ok_or_else(|| format!("contract path is not an array: {}", path.join(".")).into())
}

fn object_at<'a>(value: &'a Value, path: &[&str]) -> DynResult<&'a serde_json::Map<String, Value>> {
  let mut current = value;
  for segment in path {
    current = current.get(*segment).ok_or_else(|| format!("missing contract path: {}", path.join(".")))?;
  }
  current.as_object().ok_or_else(|| format!("contract path is not an object: {}", path.join(".")).into())
}

fn string_field<'a>(value: &'a Value, field: &str) -> DynResult<&'a str> {
  value.get(field).and_then(Value::as_str).ok_or_else(|| format!("missing string field: {field}").into())
}

fn nonempty_field(value: &Value, field: &str) -> bool {
  match value.get(field) {
    Some(Value::String(value)) => !value.is_empty(),
    Some(Value::Array(value)) => !value.is_empty(),
    Some(Value::Object(value)) => !value.is_empty(),
    _ => false,
  }
}

fn u64_field(value: &Value, field: &str) -> Result<u64, String> {
  value.get(field).and_then(Value::as_u64).ok_or_else(|| format!("missing numeric field: {field}"))
}

fn bool_field(value: &Value, field: &str) -> DynResult<bool> {
  value.get(field).and_then(Value::as_bool).ok_or_else(|| format!("missing boolean field: {field}").into())
}

fn optional_string_literal(value: &Value, field: &str) -> DynResult<String> {
  match value.get(field) {
    None | Some(Value::Null) => Ok("None".to_string()),
    Some(Value::String(value)) => Ok(format!("Some({value:?})")),
    Some(_) => Err(format!("optional field is not a string: {field}").into()),
  }
}

fn environment_name(path: &str) -> String {
  format!("AEORDB_{}", path.replace('.', "_").to_ascii_uppercase())
}

fn cli_name(path: &str) -> String {
  format!("--{}", path.replace(['.', '_'], "-"))
}

fn parse_hex_u16(value: &str) -> DynResult<u16> {
  Ok(u16::from_str_radix(value.strip_prefix("0x").ok_or("expected 0x-prefixed u16")?, 16)?)
}

fn rust_module(value: &str) -> String {
  rust_const(value).to_ascii_lowercase()
}

fn rust_const(value: &str) -> String {
  let mut output = String::new();
  let mut previous_was_lower_or_digit = false;
  let mut previous_was_separator = true;
  for character in value.chars() {
    if !character.is_ascii_alphanumeric() {
      if !output.is_empty() && !output.ends_with('_') {
        output.push('_');
      }
      previous_was_lower_or_digit = false;
      previous_was_separator = true;
      continue;
    }
    if character.is_ascii_uppercase() && previous_was_lower_or_digit && !previous_was_separator && !output.ends_with('_') {
      output.push('_');
    }
    output.push(character.to_ascii_uppercase());
    previous_was_lower_or_digit = character.is_ascii_lowercase() || character.is_ascii_digit();
    previous_was_separator = false;
  }
  output.trim_matches('_').to_string()
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn rust_identifiers_are_stable_and_collision_visible() {
    assert_eq!(rust_const("WholeEntityV1"), "WHOLE_ENTITY_V1");
    assert_eq!(rust_const("root-retirement.reason"), "ROOT_RETIREMENT_REASON");
  }

  #[test]
  fn architecture_registry_rejects_collisions_and_missing_ownership() {
    let source = include_str!("../../../aeordb-lib/spec/fixtures/v4/architecture-contract-registry.json");
    let valid: Value = serde_json::from_str(source).unwrap();
    validate_architecture(&valid).unwrap();

    let mut duplicate = valid.clone();
    duplicate["route_classes"][1]["id"] = Value::from(1);
    assert!(validate_architecture(&duplicate).unwrap_err().to_string().contains("canonically ordered"));

    let mut ownerless = valid.clone();
    ownerless["dynamic_records"][0]["retention_owner"] = Value::from("");
    assert!(validate_architecture(&ownerless).unwrap_err().to_string().contains("retention_owner"));

    let mut crash_unspecified = valid;
    crash_unspecified["hard_transitions"][0]["crash_after"] = Value::from("");
    assert!(validate_architecture(&crash_unspecified).unwrap_err().to_string().contains("crash_after"));
  }
}
