// @generated by tools/v4-reference; do not edit by hand.
// Regenerate with `aeordb-v4-reference generate-contracts`.
#![allow(dead_code)]

pub const CONTRACT_REGISTRY_SHA256: &str = "58a18bedee5816ec90f64b9f316b9571a31b6cbce818d174f83bad9e06102300";
pub const CONTRACT_REGISTRY_BLAKE3: &str = "1357a2300aad97ec5a5c1f91f0b62dff609a9c903900e5d47c4a26df70019a04";
pub const SYSTEM_FAMILY_MANIFEST_SHA256: &str = "ec31b5eb230889649252aa5bd3d5656ef86c14e5b31cc3a4138b07543208ffd1";

pub const ARCHITECTURE_REGISTRY_SHA256: &str = "d69c6a0f154ceeffac0bbbe632d994bd982ca82265f2f149cd771590f65b01c9";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RegistryValue { pub id: u16, pub name: &'static str }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EntryTypeValue { pub id: u8, pub name: &'static str, pub kv_tag: u8 }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct KvTagValue { pub id: u8, pub name: &'static str, pub entry_type: Option<u8> }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FormatLimit { pub id: &'static str, pub hard_cap: u64 }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ConfigProperty { pub id: u16, pub path: &'static str, pub environment: &'static str, pub cli: &'static str, pub kind: &'static str, pub activation: &'static str, pub owner: &'static str, pub lkg: bool, pub redaction: Option<&'static str> }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DynamicRecordContract { pub id: u16, pub name: &'static str, pub discoverability: &'static str, pub retention_owner: &'static str }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HardTransitionContract { pub id: u16, pub name: &'static str, pub selector: &'static str, pub crash_before: &'static str, pub crash_after: &'static str }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CleanupResultContract { pub id: u16, pub name: &'static str, pub behavior: &'static str, pub debt_owner: &'static str }

pub const CAPABILITY_BITS: &[RegistryValue] = &[
  RegistryValue { id: 0, name: "WholeEntityV1" },
  RegistryValue { id: 1, name: "NamespaceRootV1" },
  RegistryValue { id: 2, name: "SemanticStateV1" },
  RegistryValue { id: 3, name: "SystemFamilyRegistryV1" },
  RegistryValue { id: 4, name: "SystemControlV1" },
  RegistryValue { id: 5, name: "RootAdmissionV1" },
  RegistryValue { id: 6, name: "GlobalPublicationSequenceV1" },
  RegistryValue { id: 7, name: "IndexArtifactV1" },
  RegistryValue { id: 8, name: "IndexDefinitionV1" },
  RegistryValue { id: 9, name: "IndexPagedStoreV1" },
  RegistryValue { id: 10, name: "IndexCoverageV1" },
  RegistryValue { id: 11, name: "SparseNvtV1" },
  RegistryValue { id: 12, name: "GcArtifactV1" },
  RegistryValue { id: 13, name: "PhysicalInventoryV1" },
  RegistryValue { id: 14, name: "DurableMarkWorkspaceV1" },
  RegistryValue { id: 15, name: "QuarantineTwoMarkV1" },
  RegistryValue { id: 16, name: "ReceiptBackedVoidV1" },
  RegistryValue { id: 17, name: "RootLifecycleRetirementV1" },
  RegistryValue { id: 18, name: "LifecycleConfigV1" },
  RegistryValue { id: 19, name: "ConfigLastKnownGoodV1" },
  RegistryValue { id: 20, name: "RepairPathLatchV1" },
  RegistryValue { id: 21, name: "SideBySideMigrationV1" },
  RegistryValue { id: 22, name: "DurabilityLatchSpillV1" },
  RegistryValue { id: 23, name: "DurableTaskPinV1" },
];

pub mod capability_bit {
  pub const WHOLE_ENTITY_V1: u16 = 0;
  pub const NAMESPACE_ROOT_V1: u16 = 1;
  pub const SEMANTIC_STATE_V1: u16 = 2;
  pub const SYSTEM_FAMILY_REGISTRY_V1: u16 = 3;
  pub const SYSTEM_CONTROL_V1: u16 = 4;
  pub const ROOT_ADMISSION_V1: u16 = 5;
  pub const GLOBAL_PUBLICATION_SEQUENCE_V1: u16 = 6;
  pub const INDEX_ARTIFACT_V1: u16 = 7;
  pub const INDEX_DEFINITION_V1: u16 = 8;
  pub const INDEX_PAGED_STORE_V1: u16 = 9;
  pub const INDEX_COVERAGE_V1: u16 = 10;
  pub const SPARSE_NVT_V1: u16 = 11;
  pub const GC_ARTIFACT_V1: u16 = 12;
  pub const PHYSICAL_INVENTORY_V1: u16 = 13;
  pub const DURABLE_MARK_WORKSPACE_V1: u16 = 14;
  pub const QUARANTINE_TWO_MARK_V1: u16 = 15;
  pub const RECEIPT_BACKED_VOID_V1: u16 = 16;
  pub const ROOT_LIFECYCLE_RETIREMENT_V1: u16 = 17;
  pub const LIFECYCLE_CONFIG_V1: u16 = 18;
  pub const CONFIG_LAST_KNOWN_GOOD_V1: u16 = 19;
  pub const REPAIR_PATH_LATCH_V1: u16 = 20;
  pub const SIDE_BY_SIDE_MIGRATION_V1: u16 = 21;
  pub const DURABILITY_LATCH_SPILL_V1: u16 = 22;
  pub const DURABLE_TASK_PIN_V1: u16 = 23;
}

pub const ENTRY_TYPES: &[EntryTypeValue] = &[
  EntryTypeValue { id: 1, name: "Chunk", kv_tag: 0 },
  EntryTypeValue { id: 2, name: "FileRecord", kv_tag: 1 },
  EntryTypeValue { id: 3, name: "DirectoryIndex", kv_tag: 2 },
  EntryTypeValue { id: 4, name: "DeletionRecord", kv_tag: 3 },
  EntryTypeValue { id: 5, name: "Snapshot", kv_tag: 4 },
  EntryTypeValue { id: 6, name: "Void", kv_tag: 5 },
  EntryTypeValue { id: 7, name: "Fork", kv_tag: 7 },
  EntryTypeValue { id: 8, name: "Symlink", kv_tag: 9 },
  EntryTypeValue { id: 9, name: "IndexArtifact", kv_tag: 10 },
  EntryTypeValue { id: 10, name: "GcArtifact", kv_tag: 11 },
];

pub mod entry_type {
  pub const CHUNK: u8 = 1;
  pub const FILE_RECORD: u8 = 2;
  pub const DIRECTORY_INDEX: u8 = 3;
  pub const DELETION_RECORD: u8 = 4;
  pub const SNAPSHOT: u8 = 5;
  pub const VOID: u8 = 6;
  pub const FORK: u8 = 7;
  pub const SYMLINK: u8 = 8;
  pub const INDEX_ARTIFACT: u8 = 9;
  pub const GC_ARTIFACT: u8 = 10;
}

pub const KV_TAGS: &[KvTagValue] = &[
  KvTagValue { id: 0, name: "chunk", entry_type: Some(1) },
  KvTagValue { id: 1, name: "file_record", entry_type: Some(2) },
  KvTagValue { id: 2, name: "directory", entry_type: Some(3) },
  KvTagValue { id: 3, name: "deletion", entry_type: Some(4) },
  KvTagValue { id: 4, name: "snapshot", entry_type: Some(5) },
  KvTagValue { id: 5, name: "void", entry_type: Some(6) },
  KvTagValue { id: 6, name: "head", entry_type: None },
  KvTagValue { id: 7, name: "fork", entry_type: Some(7) },
  KvTagValue { id: 8, name: "version", entry_type: None },
  KvTagValue { id: 9, name: "symlink", entry_type: Some(8) },
  KvTagValue { id: 10, name: "index_artifact", entry_type: Some(9) },
  KvTagValue { id: 11, name: "gc_artifact", entry_type: Some(10) },
];

pub mod kv_tag {
  pub const CHUNK: u8 = 0;
  pub const FILE_RECORD: u8 = 1;
  pub const DIRECTORY: u8 = 2;
  pub const DELETION: u8 = 3;
  pub const SNAPSHOT: u8 = 4;
  pub const VOID: u8 = 5;
  pub const HEAD: u8 = 6;
  pub const FORK: u8 = 7;
  pub const VERSION: u8 = 8;
  pub const SYMLINK: u8 = 9;
  pub const INDEX_ARTIFACT: u8 = 10;
  pub const GC_ARTIFACT: u8 = 11;
}

pub const AUDIT_PIN_REASON_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "operator_investigation" },
  RegistryValue { id: 2, name: "repair_evidence" },
  RegistryValue { id: 3, name: "migration_verification" },
  RegistryValue { id: 4, name: "support_bundle" },
];

pub mod audit_pin_reason_v1 {
  pub const OPERATOR_INVESTIGATION: u16 = 1;
  pub const REPAIR_EVIDENCE: u16 = 2;
  pub const MIGRATION_VERIFICATION: u16 = 3;
  pub const SUPPORT_BUNDLE: u16 = 4;
}

pub const DURABILITY_OPERATION_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "dependency_append" },
  RegistryValue { id: 2, name: "data_barrier" },
  RegistryValue { id: 3, name: "authority_write" },
  RegistryValue { id: 4, name: "authority_barrier" },
  RegistryValue { id: 5, name: "authority_readback" },
  RegistryValue { id: 6, name: "header_ab" },
  RegistryValue { id: 7, name: "control_ab" },
  RegistryValue { id: 8, name: "parent_directory_sync" },
  RegistryValue { id: 9, name: "durable_replace" },
  RegistryValue { id: 10, name: "preallocation" },
  RegistryValue { id: 11, name: "void_claim" },
  RegistryValue { id: 12, name: "emergency_spill" },
  RegistryValue { id: 13, name: "cutover_journal" },
  RegistryValue { id: 14, name: "cutover_rename" },
  RegistryValue { id: 15, name: "shutdown_flush" },
];

pub mod durability_operation_v1 {
  pub const DEPENDENCY_APPEND: u16 = 1;
  pub const DATA_BARRIER: u16 = 2;
  pub const AUTHORITY_WRITE: u16 = 3;
  pub const AUTHORITY_BARRIER: u16 = 4;
  pub const AUTHORITY_READBACK: u16 = 5;
  pub const HEADER_AB: u16 = 6;
  pub const CONTROL_AB: u16 = 7;
  pub const PARENT_DIRECTORY_SYNC: u16 = 8;
  pub const DURABLE_REPLACE: u16 = 9;
  pub const PREALLOCATION: u16 = 10;
  pub const VOID_CLAIM: u16 = 11;
  pub const EMERGENCY_SPILL: u16 = 12;
  pub const CUTOVER_JOURNAL: u16 = 13;
  pub const CUTOVER_RENAME: u16 = 14;
  pub const SHUTDOWN_FLUSH: u16 = 15;
}

pub const GC_AUDIT_EVENT_KIND_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "mark_started" },
  RegistryValue { id: 2, name: "mark_completed" },
  RegistryValue { id: 3, name: "mark_canceled" },
  RegistryValue { id: 4, name: "root_pending" },
  RegistryValue { id: 5, name: "root_retired" },
  RegistryValue { id: 6, name: "sweep_proposed" },
  RegistryValue { id: 7, name: "sweep_committed" },
  RegistryValue { id: 8, name: "sweep_recovered" },
  RegistryValue { id: 9, name: "void_claimed" },
  RegistryValue { id: 10, name: "void_claim_settled" },
  RegistryValue { id: 11, name: "void_claim_recovered" },
  RegistryValue { id: 12, name: "corrupt_evidence" },
  RegistryValue { id: 13, name: "retention_compacted" },
  RegistryValue { id: 14, name: "gc_disabled" },
];

pub mod gc_audit_event_kind_v1 {
  pub const MARK_STARTED: u16 = 1;
  pub const MARK_COMPLETED: u16 = 2;
  pub const MARK_CANCELED: u16 = 3;
  pub const ROOT_PENDING: u16 = 4;
  pub const ROOT_RETIRED: u16 = 5;
  pub const SWEEP_PROPOSED: u16 = 6;
  pub const SWEEP_COMMITTED: u16 = 7;
  pub const SWEEP_RECOVERED: u16 = 8;
  pub const VOID_CLAIMED: u16 = 9;
  pub const VOID_CLAIM_SETTLED: u16 = 10;
  pub const VOID_CLAIM_RECOVERED: u16 = 11;
  pub const CORRUPT_EVIDENCE: u16 = 12;
  pub const RETENTION_COMPACTED: u16 = 13;
  pub const GC_DISABLED: u16 = 14;
}

pub const GC_ERROR_CLASS_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "framing" },
  RegistryValue { id: 2, name: "checksum" },
  RegistryValue { id: 3, name: "bounds_or_overlap" },
  RegistryValue { id: 4, name: "missing_edge" },
  RegistryValue { id: 5, name: "wrong_identity" },
  RegistryValue { id: 6, name: "ambiguous_control" },
  RegistryValue { id: 7, name: "incomplete_authority_walk" },
  RegistryValue { id: 8, name: "workspace_tamper_or_loss" },
  RegistryValue { id: 9, name: "policy_unavailable" },
  RegistryValue { id: 10, name: "unsupported_codec" },
];

pub mod gc_error_class_v1 {
  pub const FRAMING: u16 = 1;
  pub const CHECKSUM: u16 = 2;
  pub const BOUNDS_OR_OVERLAP: u16 = 3;
  pub const MISSING_EDGE: u16 = 4;
  pub const WRONG_IDENTITY: u16 = 5;
  pub const AMBIGUOUS_CONTROL: u16 = 6;
  pub const INCOMPLETE_AUTHORITY_WALK: u16 = 7;
  pub const WORKSPACE_TAMPER_OR_LOSS: u16 = 8;
  pub const POLICY_UNAVAILABLE: u16 = 9;
  pub const UNSUPPORTED_CODEC: u16 = 10;
}

pub const GC_OUTCOME_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "complete" },
  RegistryValue { id: 2, name: "canceled" },
  RegistryValue { id: 3, name: "failed" },
  RegistryValue { id: 4, name: "skipped" },
  RegistryValue { id: 5, name: "recovered" },
];

pub mod gc_outcome_v1 {
  pub const COMPLETE: u16 = 1;
  pub const CANCELED: u16 = 2;
  pub const FAILED: u16 = 3;
  pub const SKIPPED: u16 = 4;
  pub const RECOVERED: u16 = 5;
}

pub const GC_RUN_KIND_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "mark" },
  RegistryValue { id: 2, name: "sweep" },
  RegistryValue { id: 3, name: "physical_inventory" },
  RegistryValue { id: 4, name: "audit_compaction" },
  RegistryValue { id: 5, name: "void_reconcile" },
  RegistryValue { id: 6, name: "root_lifecycle_reconcile" },
];

pub mod gc_run_kind_v1 {
  pub const MARK: u16 = 1;
  pub const SWEEP: u16 = 2;
  pub const PHYSICAL_INVENTORY: u16 = 3;
  pub const AUDIT_COMPACTION: u16 = 4;
  pub const VOID_RECONCILE: u16 = 5;
  pub const ROOT_LIFECYCLE_RECONCILE: u16 = 6;
}

pub const MUTATION_OPERATION_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "create" },
  RegistryValue { id: 2, name: "replace" },
  RegistryValue { id: 3, name: "delete" },
  RegistryValue { id: 4, name: "activate" },
  RegistryValue { id: 5, name: "deactivate" },
  RegistryValue { id: 6, name: "promote" },
  RegistryValue { id: 7, name: "restore" },
  RegistryValue { id: 8, name: "reconcile" },
  RegistryValue { id: 9, name: "retire" },
  RegistryValue { id: 10, name: "repair" },
];

pub mod mutation_operation_v1 {
  pub const CREATE: u16 = 1;
  pub const REPLACE: u16 = 2;
  pub const DELETE: u16 = 3;
  pub const ACTIVATE: u16 = 4;
  pub const DEACTIVATE: u16 = 5;
  pub const PROMOTE: u16 = 6;
  pub const RESTORE: u16 = 7;
  pub const RECONCILE: u16 = 8;
  pub const RETIRE: u16 = 9;
  pub const REPAIR: u16 = 10;
}

pub const OS_ERROR_CLASS_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "interrupted_no_progress" },
  RegistryValue { id: 2, name: "no_space" },
  RegistryValue { id: 3, name: "quota" },
  RegistryValue { id: 4, name: "read_only" },
  RegistryValue { id: 5, name: "permission" },
  RegistryValue { id: 6, name: "media_io" },
  RegistryValue { id: 7, name: "device_lost" },
  RegistryValue { id: 8, name: "invalid_handle" },
  RegistryValue { id: 9, name: "unsupported_durability" },
  RegistryValue { id: 10, name: "checksum_readback" },
  RegistryValue { id: 11, name: "short_write" },
  RegistryValue { id: 12, name: "timeout_unknown" },
  RegistryValue { id: 13, name: "other_persistent_io" },
];

pub mod os_error_class_v1 {
  pub const INTERRUPTED_NO_PROGRESS: u16 = 1;
  pub const NO_SPACE: u16 = 2;
  pub const QUOTA: u16 = 3;
  pub const READ_ONLY: u16 = 4;
  pub const PERMISSION: u16 = 5;
  pub const MEDIA_IO: u16 = 6;
  pub const DEVICE_LOST: u16 = 7;
  pub const INVALID_HANDLE: u16 = 8;
  pub const UNSUPPORTED_DURABILITY: u16 = 9;
  pub const CHECKSUM_READBACK: u16 = 10;
  pub const SHORT_WRITE: u16 = 11;
  pub const TIMEOUT_UNKNOWN: u16 = 12;
  pub const OTHER_PERSISTENT_IO: u16 = 13;
}

pub const REPAIR_CORRUPTION_CLASS_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "entity_framing" },
  RegistryValue { id: 2, name: "entity_integrity" },
  RegistryValue { id: 3, name: "locator_missing" },
  RegistryValue { id: 4, name: "locator_identity_mismatch" },
  RegistryValue { id: 5, name: "btree_missing_node" },
  RegistryValue { id: 6, name: "btree_malformed_node" },
  RegistryValue { id: 7, name: "btree_cycle_or_order" },
  RegistryValue { id: 8, name: "authority_missing_or_ambiguous" },
  RegistryValue { id: 9, name: "semantic_closure" },
  RegistryValue { id: 10, name: "system_family_incomplete" },
  RegistryValue { id: 11, name: "physical_overlap_or_bounds" },
  RegistryValue { id: 12, name: "control_ambiguous_or_corrupt" },
  RegistryValue { id: 13, name: "unsupported_required_format" },
];

pub mod repair_corruption_class_v1 {
  pub const ENTITY_FRAMING: u16 = 1;
  pub const ENTITY_INTEGRITY: u16 = 2;
  pub const LOCATOR_MISSING: u16 = 3;
  pub const LOCATOR_IDENTITY_MISMATCH: u16 = 4;
  pub const BTREE_MISSING_NODE: u16 = 5;
  pub const BTREE_MALFORMED_NODE: u16 = 6;
  pub const BTREE_CYCLE_OR_ORDER: u16 = 7;
  pub const AUTHORITY_MISSING_OR_AMBIGUOUS: u16 = 8;
  pub const SEMANTIC_CLOSURE: u16 = 9;
  pub const SYSTEM_FAMILY_INCOMPLETE: u16 = 10;
  pub const PHYSICAL_OVERLAP_OR_BOUNDS: u16 = 11;
  pub const CONTROL_AMBIGUOUS_OR_CORRUPT: u16 = 12;
  pub const UNSUPPORTED_REQUIRED_FORMAT: u16 = 13;
}

pub const RETRY_CLASS_V1: &[RegistryValue] = &[
  RegistryValue { id: 0, name: "none" },
  RegistryValue { id: 1, name: "immediate" },
  RegistryValue { id: 2, name: "bounded_backoff" },
  RegistryValue { id: 3, name: "after_dependency" },
  RegistryValue { id: 4, name: "after_repair" },
  RegistryValue { id: 5, name: "never" },
];

pub mod retry_class_v1 {
  pub const NONE: u16 = 0;
  pub const IMMEDIATE: u16 = 1;
  pub const BOUNDED_BACKOFF: u16 = 2;
  pub const AFTER_DEPENDENCY: u16 = 3;
  pub const AFTER_REPAIR: u16 = 4;
  pub const NEVER: u16 = 5;
}

pub const ROOT_RETIREMENT_REASON_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "ordinary_gc_unreachable" },
  RegistryValue { id: 2, name: "explicit_operator_retirement" },
];

pub mod root_retirement_reason_v1 {
  pub const ORDINARY_GC_UNREACHABLE: u16 = 1;
  pub const EXPLICIT_OPERATOR_RETIREMENT: u16 = 2;
}

pub const STABLE_REASON_V1: &[RegistryValue] = &[
  RegistryValue { id: 0, name: "none_or_success" },
  RegistryValue { id: 1, name: "requested" },
  RegistryValue { id: 2, name: "source_changed" },
  RegistryValue { id: 3, name: "incomplete_coverage" },
  RegistryValue { id: 4, name: "dependency_unavailable" },
  RegistryValue { id: 5, name: "unsupported_definition_or_format" },
  RegistryValue { id: 6, name: "corrupt_derived_artifact" },
  RegistryValue { id: 7, name: "corrupt_authority" },
  RegistryValue { id: 8, name: "resource_admission" },
  RegistryValue { id: 9, name: "canceled" },
  RegistryValue { id: 10, name: "shutdown" },
  RegistryValue { id: 11, name: "retryable_io" },
  RegistryValue { id: 12, name: "permanent_io" },
  RegistryValue { id: 13, name: "stale_fence" },
  RegistryValue { id: 14, name: "invalid_configuration" },
  RegistryValue { id: 15, name: "root_unavailable" },
  RegistryValue { id: 16, name: "rebuild_required" },
  RegistryValue { id: 17, name: "repair_required" },
  RegistryValue { id: 18, name: "migration_reset" },
  RegistryValue { id: 19, name: "capture_gap" },
  RegistryValue { id: 20, name: "policy_disabled" },
  RegistryValue { id: 21, name: "integrity_mismatch" },
  RegistryValue { id: 22, name: "uncertain_completion" },
  RegistryValue { id: 23, name: "collision_alarm" },
  RegistryValue { id: 24, name: "unknown_protected_family" },
];

pub mod stable_reason_v1 {
  pub const NONE_OR_SUCCESS: u16 = 0;
  pub const REQUESTED: u16 = 1;
  pub const SOURCE_CHANGED: u16 = 2;
  pub const INCOMPLETE_COVERAGE: u16 = 3;
  pub const DEPENDENCY_UNAVAILABLE: u16 = 4;
  pub const UNSUPPORTED_DEFINITION_OR_FORMAT: u16 = 5;
  pub const CORRUPT_DERIVED_ARTIFACT: u16 = 6;
  pub const CORRUPT_AUTHORITY: u16 = 7;
  pub const RESOURCE_ADMISSION: u16 = 8;
  pub const CANCELED: u16 = 9;
  pub const SHUTDOWN: u16 = 10;
  pub const RETRYABLE_IO: u16 = 11;
  pub const PERMANENT_IO: u16 = 12;
  pub const STALE_FENCE: u16 = 13;
  pub const INVALID_CONFIGURATION: u16 = 14;
  pub const ROOT_UNAVAILABLE: u16 = 15;
  pub const REBUILD_REQUIRED: u16 = 16;
  pub const REPAIR_REQUIRED: u16 = 17;
  pub const MIGRATION_RESET: u16 = 18;
  pub const CAPTURE_GAP: u16 = 19;
  pub const POLICY_DISABLED: u16 = 20;
  pub const INTEGRITY_MISMATCH: u16 = 21;
  pub const UNCERTAIN_COMPLETION: u16 = 22;
  pub const COLLISION_ALARM: u16 = 23;
  pub const UNKNOWN_PROTECTED_FAMILY: u16 = 24;
}

pub const TASK_KIND_V1: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "index_build" },
  RegistryValue { id: 2, name: "reindex" },
  RegistryValue { id: 3, name: "gc_mark" },
  RegistryValue { id: 4, name: "gc_sweep" },
  RegistryValue { id: 5, name: "physical_inventory" },
  RegistryValue { id: 6, name: "backup_export" },
  RegistryValue { id: 7, name: "backup_import" },
  RegistryValue { id: 8, name: "format_migration" },
  RegistryValue { id: 9, name: "repair" },
  RegistryValue { id: 10, name: "compaction" },
  RegistryValue { id: 11, name: "peer_sync" },
];

pub mod task_kind_v1 {
  pub const INDEX_BUILD: u16 = 1;
  pub const REINDEX: u16 = 2;
  pub const GC_MARK: u16 = 3;
  pub const GC_SWEEP: u16 = 4;
  pub const PHYSICAL_INVENTORY: u16 = 5;
  pub const BACKUP_EXPORT: u16 = 6;
  pub const BACKUP_IMPORT: u16 = 7;
  pub const FORMAT_MIGRATION: u16 = 8;
  pub const REPAIR: u16 = 9;
  pub const COMPACTION: u16 = 10;
  pub const PEER_SYNC: u16 = 11;
}

pub const FORMAT_LIMITS: &[FormatLimit] = &[
  FormatLimit { id: "database-header-v4", hard_cap: 2048 },
  FormatLimit { id: "whole-entity-v1", hard_cap: 4294967295 },
  FormatLimit { id: "directory-index-v1", hard_cap: 236 },
  FormatLimit { id: "semantic-object-v1", hard_cap: 1048576 },
  FormatLimit { id: "dependency-table-v1", hard_cap: 262144 },
  FormatLimit { id: "invocation-policy-v1", hard_cap: 128 },
  FormatLimit { id: "parser-resolution-plan-v1", hard_cap: 131072 },
  FormatLimit { id: "source-selector-v1", hard_cap: 4096 },
  FormatLimit { id: "value-store-definition-v1", hard_cap: 524288 },
  FormatLimit { id: "canonical-config-value-v1", hard_cap: 262144 },
  FormatLimit { id: "scope-definition-v1", hard_cap: 65536 },
  FormatLimit { id: "index-artifact-v1", hard_cap: 67108864 },
  FormatLimit { id: "converter-definition-v1", hard_cap: 65536 },
  FormatLimit { id: "field-index-definition-v1", hard_cap: 262144 },
  FormatLimit { id: "gc-artifact-v1", hard_cap: 67108864 },
  FormatLimit { id: "gc-mark-workspace-manifest-v1", hard_cap: 8388608 },
  FormatLimit { id: "gc-mark-workspace-object-v1", hard_cap: 67108864 },
  FormatLimit { id: "system-control-v1", hard_cap: 67108900 },
  FormatLimit { id: "cutover-journal-v1", hard_cap: 2048 },
  FormatLimit { id: "logical-position-v1", hard_cap: 1048576 },
  FormatLimit { id: "system-family-registry-v1", hard_cap: 1048576 },
];

pub mod format_hard_cap {
  pub const DATABASE_HEADER_V4: u64 = 2048;
  pub const WHOLE_ENTITY_V1: u64 = 4294967295;
  pub const DIRECTORY_INDEX_V1: u64 = 236;
  pub const SEMANTIC_OBJECT_V1: u64 = 1048576;
  pub const DEPENDENCY_TABLE_V1: u64 = 262144;
  pub const INVOCATION_POLICY_V1: u64 = 128;
  pub const PARSER_RESOLUTION_PLAN_V1: u64 = 131072;
  pub const SOURCE_SELECTOR_V1: u64 = 4096;
  pub const VALUE_STORE_DEFINITION_V1: u64 = 524288;
  pub const CANONICAL_CONFIG_VALUE_V1: u64 = 262144;
  pub const SCOPE_DEFINITION_V1: u64 = 65536;
  pub const INDEX_ARTIFACT_V1: u64 = 67108864;
  pub const CONVERTER_DEFINITION_V1: u64 = 65536;
  pub const FIELD_INDEX_DEFINITION_V1: u64 = 262144;
  pub const GC_ARTIFACT_V1: u64 = 67108864;
  pub const GC_MARK_WORKSPACE_MANIFEST_V1: u64 = 8388608;
  pub const GC_MARK_WORKSPACE_OBJECT_V1: u64 = 67108864;
  pub const SYSTEM_CONTROL_V1: u64 = 67108900;
  pub const CUTOVER_JOURNAL_V1: u64 = 2048;
  pub const LOGICAL_POSITION_V1: u64 = 1048576;
  pub const SYSTEM_FAMILY_REGISTRY_V1: u64 = 1048576;
}

pub const SYSTEM_FAMILIES: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "root_index_config" },
  RegistryValue { id: 2, name: "descendant_index_config" },
  RegistryValue { id: 3, name: "parser_config" },
  RegistryValue { id: 4, name: "lifecycle_config" },
  RegistryValue { id: 5, name: "cron_config" },
  RegistryValue { id: 6, name: "webhook_config" },
  RegistryValue { id: 7, name: "cors_config" },
  RegistryValue { id: 8, name: "descendant_config" },
  RegistryValue { id: 9, name: "runtime_config" },
  RegistryValue { id: 16, name: "users" },
  RegistryValue { id: 17, name: "groups" },
  RegistryValue { id: 18, name: "central_permissions" },
  RegistryValue { id: 19, name: "api_keys" },
  RegistryValue { id: 20, name: "refresh_tokens" },
  RegistryValue { id: 21, name: "magic_links" },
  RegistryValue { id: 22, name: "system_config" },
  RegistryValue { id: 23, name: "email_config" },
  RegistryValue { id: 24, name: "join_audit" },
  RegistryValue { id: 25, name: "namespace_permissions" },
  RegistryValue { id: 26, name: "conflicts" },
  RegistryValue { id: 32, name: "node_id" },
  RegistryValue { id: 33, name: "cluster_peers" },
  RegistryValue { id: 34, name: "sync_peers" },
  RegistryValue { id: 48, name: "legacy_plugins" },
  RegistryValue { id: 49, name: "plugin_aliases" },
  RegistryValue { id: 50, name: "plugin_artifacts" },
  RegistryValue { id: 51, name: "semantic_objects" },
  RegistryValue { id: 64, name: "snapshots" },
  RegistryValue { id: 65, name: "forks" },
  RegistryValue { id: 66, name: "background_tasks" },
  RegistryValue { id: 67, name: "control_store" },
  RegistryValue { id: 68, name: "legacy_root_lifecycle" },
  RegistryValue { id: 80, name: "index_artifacts" },
  RegistryValue { id: 81, name: "gc_artifacts" },
  RegistryValue { id: 82, name: "deletion_records" },
  RegistryValue { id: 83, name: "void_allocator" },
  RegistryValue { id: 84, name: "database_authority" },
  RegistryValue { id: 85, name: "kv_authority" },
  RegistryValue { id: 86, name: "database_nvt" },
  RegistryValue { id: 87, name: "wal_publication" },
  RegistryValue { id: 96, name: "legacy_indexes" },
  RegistryValue { id: 97, name: "nested_logs" },
  RegistryValue { id: 98, name: "legacy_snapshots" },
  RegistryValue { id: 99, name: "legacy_aliases" },
  RegistryValue { id: 112, name: "emergency_spill" },
  RegistryValue { id: 113, name: "external_workspaces" },
];

pub mod system_family {
  pub const ROOT_INDEX_CONFIG: u16 = 0x0001;
  pub const DESCENDANT_INDEX_CONFIG: u16 = 0x0002;
  pub const PARSER_CONFIG: u16 = 0x0003;
  pub const LIFECYCLE_CONFIG: u16 = 0x0004;
  pub const CRON_CONFIG: u16 = 0x0005;
  pub const WEBHOOK_CONFIG: u16 = 0x0006;
  pub const CORS_CONFIG: u16 = 0x0007;
  pub const DESCENDANT_CONFIG: u16 = 0x0008;
  pub const RUNTIME_CONFIG: u16 = 0x0009;
  pub const USERS: u16 = 0x0010;
  pub const GROUPS: u16 = 0x0011;
  pub const CENTRAL_PERMISSIONS: u16 = 0x0012;
  pub const API_KEYS: u16 = 0x0013;
  pub const REFRESH_TOKENS: u16 = 0x0014;
  pub const MAGIC_LINKS: u16 = 0x0015;
  pub const SYSTEM_CONFIG: u16 = 0x0016;
  pub const EMAIL_CONFIG: u16 = 0x0017;
  pub const JOIN_AUDIT: u16 = 0x0018;
  pub const NAMESPACE_PERMISSIONS: u16 = 0x0019;
  pub const CONFLICTS: u16 = 0x001a;
  pub const NODE_ID: u16 = 0x0020;
  pub const CLUSTER_PEERS: u16 = 0x0021;
  pub const SYNC_PEERS: u16 = 0x0022;
  pub const LEGACY_PLUGINS: u16 = 0x0030;
  pub const PLUGIN_ALIASES: u16 = 0x0031;
  pub const PLUGIN_ARTIFACTS: u16 = 0x0032;
  pub const SEMANTIC_OBJECTS: u16 = 0x0033;
  pub const SNAPSHOTS: u16 = 0x0040;
  pub const FORKS: u16 = 0x0041;
  pub const BACKGROUND_TASKS: u16 = 0x0042;
  pub const CONTROL_STORE: u16 = 0x0043;
  pub const LEGACY_ROOT_LIFECYCLE: u16 = 0x0044;
  pub const INDEX_ARTIFACTS: u16 = 0x0050;
  pub const GC_ARTIFACTS: u16 = 0x0051;
  pub const DELETION_RECORDS: u16 = 0x0052;
  pub const VOID_ALLOCATOR: u16 = 0x0053;
  pub const DATABASE_AUTHORITY: u16 = 0x0054;
  pub const KV_AUTHORITY: u16 = 0x0055;
  pub const DATABASE_NVT: u16 = 0x0056;
  pub const WAL_PUBLICATION: u16 = 0x0057;
  pub const LEGACY_INDEXES: u16 = 0x0060;
  pub const NESTED_LOGS: u16 = 0x0061;
  pub const LEGACY_SNAPSHOTS: u16 = 0x0062;
  pub const LEGACY_ALIASES: u16 = 0x0063;
  pub const EMERGENCY_SPILL: u16 = 0x0070;
  pub const EXTERNAL_WORKSPACES: u16 = 0x0071;
  pub const UNKNOWN_PROTECTED: u16 = 0xfffe;
}
pub const ROUTE_CLASSES: &[RegistryValue] = &[
  RegistryValue { id: 1, name: "single_root_namespace" },
  RegistryValue { id: 2, name: "historical_aliases" },
  RegistryValue { id: 3, name: "multi_root" },
  RegistryValue { id: 4, name: "content_staging" },
  RegistryValue { id: 5, name: "hash_retrieval" },
  RegistryValue { id: 6, name: "operational_auth_system" },
  RegistryValue { id: 7, name: "mutation" },
];

pub mod route_class {
  pub const SINGLE_ROOT_NAMESPACE: u16 = 1;
  pub const HISTORICAL_ALIASES: u16 = 2;
  pub const MULTI_ROOT: u16 = 3;
  pub const CONTENT_STAGING: u16 = 4;
  pub const HASH_RETRIEVAL: u16 = 5;
  pub const OPERATIONAL_AUTH_SYSTEM: u16 = 6;
  pub const MUTATION: u16 = 7;
}

pub const CONFIGURATION_PROPERTIES: &[ConfigProperty] = &[
  ConfigProperty { id: 1, path: "memory.soft_limit_bytes", environment: "AEORDB_MEMORY_SOFT_LIMIT_BYTES", cli: "--memory-soft-limit-bytes", kind: "bytes", activation: "startup_bound", owner: "memory_coordinator", lkg: true, redaction: None },
  ConfigProperty { id: 2, path: "memory.hard_limit_bytes", environment: "AEORDB_MEMORY_HARD_LIMIT_BYTES", cli: "--memory-hard-limit-bytes", kind: "bytes", activation: "startup_bound", owner: "memory_coordinator", lkg: true, redaction: None },
  ConfigProperty { id: 3, path: "memory.host_available_floor_bytes", environment: "AEORDB_MEMORY_HOST_AVAILABLE_FLOOR_BYTES", cli: "--memory-host-available-floor-bytes", kind: "bytes", activation: "dynamically_staged", owner: "memory_coordinator", lkg: true, redaction: None },
  ConfigProperty { id: 4, path: "memory.emergency_reserve_bytes", environment: "AEORDB_MEMORY_EMERGENCY_RESERVE_BYTES", cli: "--memory-emergency-reserve-bytes", kind: "bytes", activation: "startup_bound", owner: "memory_coordinator", lkg: true, redaction: None },
  ConfigProperty { id: 5, path: "cache.index_clean_max_bytes", environment: "AEORDB_CACHE_INDEX_CLEAN_MAX_BYTES", cli: "--cache-index-clean-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "index_cache", lkg: true, redaction: None },
  ConfigProperty { id: 6, path: "cache.index_clean_ttl_seconds", environment: "AEORDB_CACHE_INDEX_CLEAN_TTL_SECONDS", cli: "--cache-index-clean-ttl-seconds", kind: "seconds", activation: "dynamically_staged", owner: "index_cache", lkg: true, redaction: None },
  ConfigProperty { id: 7, path: "cache.directory_max_bytes", environment: "AEORDB_CACHE_DIRECTORY_MAX_BYTES", cli: "--cache-directory-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "directory_cache", lkg: true, redaction: None },
  ConfigProperty { id: 8, path: "cache.kv_resident_max_bytes", environment: "AEORDB_CACHE_KV_RESIDENT_MAX_BYTES", cli: "--cache-kv-resident-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "kv_residency", lkg: true, redaction: None },
  ConfigProperty { id: 9, path: "cache.query_plan_max_bytes", environment: "AEORDB_CACHE_QUERY_PLAN_MAX_BYTES", cli: "--cache-query-plan-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "query_plan_cache", lkg: true, redaction: None },
  ConfigProperty { id: 10, path: "index.mutation_buffer_max_bytes", environment: "AEORDB_INDEX_MUTATION_BUFFER_MAX_BYTES", cli: "--index-mutation-buffer-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "index_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 11, path: "index.flush_after_mutations", environment: "AEORDB_INDEX_FLUSH_AFTER_MUTATIONS", cli: "--index-flush-after-mutations", kind: "count", activation: "dynamically_staged", owner: "index_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 12, path: "index.flush_after_seconds", environment: "AEORDB_INDEX_FLUSH_AFTER_SECONDS", cli: "--index-flush-after-seconds", kind: "seconds", activation: "dynamically_staged", owner: "index_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 13, path: "index.publication_batch_max_bytes", environment: "AEORDB_INDEX_PUBLICATION_BATCH_MAX_BYTES", cli: "--index-publication-batch-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "index_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 14, path: "garbage_collection.mark_memory_preferred_bytes", environment: "AEORDB_GARBAGE_COLLECTION_MARK_MEMORY_PREFERRED_BYTES", cli: "--garbage-collection-mark-memory-preferred-bytes", kind: "bytes", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 15, path: "garbage_collection.mark_memory_minimum_bytes", environment: "AEORDB_GARBAGE_COLLECTION_MARK_MEMORY_MINIMUM_BYTES", cli: "--garbage-collection-mark-memory-minimum-bytes", kind: "bytes", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 16, path: "garbage_collection.mark_scratch_free_reserve_bytes", environment: "AEORDB_GARBAGE_COLLECTION_MARK_SCRATCH_FREE_RESERVE_BYTES", cli: "--garbage-collection-mark-scratch-free-reserve-bytes", kind: "bytes", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 17, path: "garbage_collection.mark_scratch_max_bytes", environment: "AEORDB_GARBAGE_COLLECTION_MARK_SCRATCH_MAX_BYTES", cli: "--garbage-collection-mark-scratch-max-bytes", kind: "optional_bytes", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 18, path: "garbage_collection.checkpoint_after_seconds", environment: "AEORDB_GARBAGE_COLLECTION_CHECKPOINT_AFTER_SECONDS", cli: "--garbage-collection-checkpoint-after-seconds", kind: "seconds", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 19, path: "garbage_collection.checkpoint_after_dirty_bytes", environment: "AEORDB_GARBAGE_COLLECTION_CHECKPOINT_AFTER_DIRTY_BYTES", cli: "--garbage-collection-checkpoint-after-dirty-bytes", kind: "bytes", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 20, path: "garbage_collection.mark_workspace_root", environment: "AEORDB_GARBAGE_COLLECTION_MARK_WORKSPACE_ROOT", cli: "--garbage-collection-mark-workspace-root", kind: "path_or_auto", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: Some("root_only_path") },
  ConfigProperty { id: 21, path: "io.read_prefetch_bytes", environment: "AEORDB_IO_READ_PREFETCH_BYTES", cli: "--io-read-prefetch-bytes", kind: "bytes", activation: "dynamically_staged", owner: "read_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 22, path: "io.read_coalesce_max_bytes", environment: "AEORDB_IO_READ_COALESCE_MAX_BYTES", cli: "--io-read-coalesce-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "read_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 23, path: "query.per_request_memory_bytes", environment: "AEORDB_QUERY_PER_REQUEST_MEMORY_BYTES", cli: "--query-per-request-memory-bytes", kind: "bytes", activation: "dynamically_staged", owner: "query_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 24, path: "query.global_memory_bytes", environment: "AEORDB_QUERY_GLOBAL_MEMORY_BYTES", cli: "--query-global-memory-bytes", kind: "bytes", activation: "dynamically_staged", owner: "query_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 25, path: "query.position_scan_buffer_bytes", environment: "AEORDB_QUERY_POSITION_SCAN_BUFFER_BYTES", cli: "--query-position-scan-buffer-bytes", kind: "bytes", activation: "dynamically_staged", owner: "query_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 26, path: "durability.group_commit_max_bytes", environment: "AEORDB_DURABILITY_GROUP_COMMIT_MAX_BYTES", cli: "--durability-group-commit-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "durability_coordinator", lkg: true, redaction: None },
  ConfigProperty { id: 27, path: "durability.group_commit_max_delay_ms", environment: "AEORDB_DURABILITY_GROUP_COMMIT_MAX_DELAY_MS", cli: "--durability-group-commit-max-delay-ms", kind: "milliseconds", activation: "dynamically_staged", owner: "durability_coordinator", lkg: true, redaction: None },
  ConfigProperty { id: 28, path: "maintenance.max_concurrent_tasks", environment: "AEORDB_MAINTENANCE_MAX_CONCURRENT_TASKS", cli: "--maintenance-max-concurrent-tasks", kind: "count", activation: "next_run_captured", owner: "task_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 29, path: "recovery.emergency_spill_dir", environment: "AEORDB_RECOVERY_EMERGENCY_SPILL_DIR", cli: "--recovery-emergency-spill-dir", kind: "path_or_auto", activation: "startup_bound", owner: "recovery_runtime", lkg: true, redaction: Some("root_only_path") },
  ConfigProperty { id: 30, path: "recovery.emergency_spill_max_bytes", environment: "AEORDB_RECOVERY_EMERGENCY_SPILL_MAX_BYTES", cli: "--recovery-emergency-spill-max-bytes", kind: "bytes", activation: "dynamically_staged", owner: "recovery_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 31, path: "shutdown.operation_wait_seconds", environment: "AEORDB_SHUTDOWN_OPERATION_WAIT_SECONDS", cli: "--shutdown-operation-wait-seconds", kind: "seconds", activation: "dynamically_staged", owner: "shutdown_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 32, path: "migration.capture_max_bytes", environment: "AEORDB_MIGRATION_CAPTURE_MAX_BYTES", cli: "--migration-capture-max-bytes", kind: "bytes", activation: "next_run_captured", owner: "migration_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 33, path: "migration.capture_free_reserve_bytes", environment: "AEORDB_MIGRATION_CAPTURE_FREE_RESERVE_BYTES", cli: "--migration-capture-free-reserve-bytes", kind: "bytes", activation: "next_run_captured", owner: "migration_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 34, path: "migration.checkpoint_after_seconds", environment: "AEORDB_MIGRATION_CHECKPOINT_AFTER_SECONDS", cli: "--migration-checkpoint-after-seconds", kind: "seconds", activation: "next_run_captured", owner: "migration_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 35, path: "garbage_collection.root_expiry_retention_seconds", environment: "AEORDB_GARBAGE_COLLECTION_ROOT_EXPIRY_RETENTION_SECONDS", cli: "--garbage-collection-root-expiry-retention-seconds", kind: "seconds", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 36, path: "garbage_collection.root_expiry_max_bytes", environment: "AEORDB_GARBAGE_COLLECTION_ROOT_EXPIRY_MAX_BYTES", cli: "--garbage-collection-root-expiry-max-bytes", kind: "bytes", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 37, path: "garbage_collection.root_lifecycle_hard_max_bytes", environment: "AEORDB_GARBAGE_COLLECTION_ROOT_LIFECYCLE_HARD_MAX_BYTES", cli: "--garbage-collection-root-lifecycle-hard-max-bytes", kind: "bytes", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 38, path: "lifecycle.snapshot_writes_enabled", environment: "AEORDB_LIFECYCLE_SNAPSHOT_WRITES_ENABLED", cli: "--lifecycle-snapshot-writes-enabled", kind: "boolean", activation: "dynamically_staged", owner: "lifecycle_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 39, path: "lifecycle.snapshot_retention_auto_months", environment: "AEORDB_LIFECYCLE_SNAPSHOT_RETENTION_AUTO_MONTHS", cli: "--lifecycle-snapshot-retention-auto-months", kind: "months", activation: "next_run_captured", owner: "lifecycle_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 40, path: "lifecycle.snapshot_retention_manual_months", environment: "AEORDB_LIFECYCLE_SNAPSHOT_RETENTION_MANUAL_MONTHS", cli: "--lifecycle-snapshot-retention-manual-months", kind: "months", activation: "next_run_captured", owner: "lifecycle_runtime", lkg: true, redaction: None },
  ConfigProperty { id: 41, path: "lifecycle.garbage_collection_pending_delete_grace_seconds", environment: "AEORDB_LIFECYCLE_GARBAGE_COLLECTION_PENDING_DELETE_GRACE_SECONDS", cli: "--lifecycle-garbage-collection-pending-delete-grace-seconds", kind: "seconds", activation: "next_run_captured", owner: "gc_runtime", lkg: true, redaction: None },
];

pub mod config_property_id {
  pub const MEMORY_SOFT_LIMIT_BYTES: u16 = 1;
  pub const MEMORY_HARD_LIMIT_BYTES: u16 = 2;
  pub const MEMORY_HOST_AVAILABLE_FLOOR_BYTES: u16 = 3;
  pub const MEMORY_EMERGENCY_RESERVE_BYTES: u16 = 4;
  pub const CACHE_INDEX_CLEAN_MAX_BYTES: u16 = 5;
  pub const CACHE_INDEX_CLEAN_TTL_SECONDS: u16 = 6;
  pub const CACHE_DIRECTORY_MAX_BYTES: u16 = 7;
  pub const CACHE_KV_RESIDENT_MAX_BYTES: u16 = 8;
  pub const CACHE_QUERY_PLAN_MAX_BYTES: u16 = 9;
  pub const INDEX_MUTATION_BUFFER_MAX_BYTES: u16 = 10;
  pub const INDEX_FLUSH_AFTER_MUTATIONS: u16 = 11;
  pub const INDEX_FLUSH_AFTER_SECONDS: u16 = 12;
  pub const INDEX_PUBLICATION_BATCH_MAX_BYTES: u16 = 13;
  pub const GARBAGE_COLLECTION_MARK_MEMORY_PREFERRED_BYTES: u16 = 14;
  pub const GARBAGE_COLLECTION_MARK_MEMORY_MINIMUM_BYTES: u16 = 15;
  pub const GARBAGE_COLLECTION_MARK_SCRATCH_FREE_RESERVE_BYTES: u16 = 16;
  pub const GARBAGE_COLLECTION_MARK_SCRATCH_MAX_BYTES: u16 = 17;
  pub const GARBAGE_COLLECTION_CHECKPOINT_AFTER_SECONDS: u16 = 18;
  pub const GARBAGE_COLLECTION_CHECKPOINT_AFTER_DIRTY_BYTES: u16 = 19;
  pub const GARBAGE_COLLECTION_MARK_WORKSPACE_ROOT: u16 = 20;
  pub const IO_READ_PREFETCH_BYTES: u16 = 21;
  pub const IO_READ_COALESCE_MAX_BYTES: u16 = 22;
  pub const QUERY_PER_REQUEST_MEMORY_BYTES: u16 = 23;
  pub const QUERY_GLOBAL_MEMORY_BYTES: u16 = 24;
  pub const QUERY_POSITION_SCAN_BUFFER_BYTES: u16 = 25;
  pub const DURABILITY_GROUP_COMMIT_MAX_BYTES: u16 = 26;
  pub const DURABILITY_GROUP_COMMIT_MAX_DELAY_MS: u16 = 27;
  pub const MAINTENANCE_MAX_CONCURRENT_TASKS: u16 = 28;
  pub const RECOVERY_EMERGENCY_SPILL_DIR: u16 = 29;
  pub const RECOVERY_EMERGENCY_SPILL_MAX_BYTES: u16 = 30;
  pub const SHUTDOWN_OPERATION_WAIT_SECONDS: u16 = 31;
  pub const MIGRATION_CAPTURE_MAX_BYTES: u16 = 32;
  pub const MIGRATION_CAPTURE_FREE_RESERVE_BYTES: u16 = 33;
  pub const MIGRATION_CHECKPOINT_AFTER_SECONDS: u16 = 34;
  pub const GARBAGE_COLLECTION_ROOT_EXPIRY_RETENTION_SECONDS: u16 = 35;
  pub const GARBAGE_COLLECTION_ROOT_EXPIRY_MAX_BYTES: u16 = 36;
  pub const GARBAGE_COLLECTION_ROOT_LIFECYCLE_HARD_MAX_BYTES: u16 = 37;
  pub const LIFECYCLE_SNAPSHOT_WRITES_ENABLED: u16 = 38;
  pub const LIFECYCLE_SNAPSHOT_RETENTION_AUTO_MONTHS: u16 = 39;
  pub const LIFECYCLE_SNAPSHOT_RETENTION_MANUAL_MONTHS: u16 = 40;
  pub const LIFECYCLE_GARBAGE_COLLECTION_PENDING_DELETE_GRACE_SECONDS: u16 = 41;
}

pub const DYNAMIC_RECORDS: &[DynamicRecordContract] = &[
  DynamicRecordContract { id: 1, name: "system_control", discoverability: "protected control subtree plus selected A/B or immutable identity", retention_owner: "control_store" },
  DynamicRecordContract { id: 2, name: "index_artifact", discoverability: "IndexArtifact EntryType plus owning manifests and active-generation controls", retention_owner: "index_artifact_retention" },
  DynamicRecordContract { id: 3, name: "gc_artifact", discoverability: "GcArtifact EntryType plus selected GC controls", retention_owner: "gc_artifact_retention" },
  DynamicRecordContract { id: 4, name: "external_mark_workspace", discoverability: "workspace header binds database, physical instance, run, layout, and root snapshot", retention_owner: "gc_workspace_retention" },
  DynamicRecordContract { id: 5, name: "emergency_spill", discoverability: "all configured and OS fallback roots plus spill catalog and embedded database identity", retention_owner: "repair_spill_replay" },
  DynamicRecordContract { id: 6, name: "migration_capture", discoverability: "selected migration lease/progress control plus external capture manifest", retention_owner: "migration_state_machine" },
  DynamicRecordContract { id: 7, name: "task_checkpoint", discoverability: "task ID and selected checkpoint control or task-owned external manifest", retention_owner: "task_runtime" },
  DynamicRecordContract { id: 8, name: "retirement_acceleration_journal", discoverability: "selected checkpoint and monotonic write-sequence interval", retention_owner: "physical_inventory" },
];

pub const HARD_TRANSITIONS: &[HardTransitionContract] = &[
  HardTransitionContract { id: 1, name: "database_header_ab", selector: "highest valid sequence; equal divergent sequence is corruption", crash_before: "old slot remains selected", crash_after: "new valid slot is selected and read back" },
  HardTransitionContract { id: 2, name: "system_control_ab", selector: "highest valid sequence with repeated identity", crash_before: "old control remains selected", crash_after: "new control selected only after dependency barrier" },
  HardTransitionContract { id: 3, name: "namespace_root_publication", selector: "selected DatabaseHeader namespace_root_hash", crash_before: "previous root remains authoritative", crash_after: "new closed root and dependencies are authoritative" },
  HardTransitionContract { id: 4, name: "index_active_generation", selector: "selected index operation/registry control", crash_before: "previous generation or authoritative fallback", crash_after: "new generation used only with valid coverage" },
  HardTransitionContract { id: 5, name: "gc_mark_publication", selector: "selected GC run/checkpoint control", crash_before: "no quarantine eligibility from incomplete mark", crash_after: "complete mark becomes one eligibility observation" },
  HardTransitionContract { id: 6, name: "root_lifecycle_retirement", selector: "selected root lifecycle state", crash_before: "root remains pending/readable", crash_after: "retired root returns deterministic gone before physical reclaim" },
  HardTransitionContract { id: 7, name: "sweep_void_publication", selector: "selected sweep receipt then selected Void catalog", crash_before: "space leaks and is not allocatable", crash_after: "only receipt-backed ranges become allocator authority" },
  HardTransitionContract { id: 8, name: "void_claim_settlement", selector: "selected Void catalog minus durable immutable claims", crash_before: "claimed range remains unavailable", crash_after: "settled claim has exactly one owner or returns to catalog" },
  HardTransitionContract { id: 9, name: "durability_latch", selector: "selected durability-latch control", crash_before: "ambiguous write is recovered or startup fails closed", crash_after: "database opens read-only until explicit repair clears latch" },
  HardTransitionContract { id: 10, name: "side_by_side_cutover", selector: "external cutover A/B journal plus physical database identity", crash_before: "v3 remains production authority", crash_after: "v4 becomes authority only after verified durable replace" },
  HardTransitionContract { id: 11, name: "writer_fence_epoch", selector: "selected DatabaseHeader writer_fence_epoch", crash_before: "prior process cannot publish under a new epoch", crash_after: "all new publication guards recheck the selected epoch" },
  HardTransitionContract { id: 12, name: "task_checkpoint_publication", selector: "highest valid task checkpoint sequence", crash_before: "repeat bounded uncheckpointed work", crash_after: "resume only after identity and continuity validation" },
];

pub const CLEANUP_RESULT_CLASSES: &[CleanupResultContract] = &[
  CleanupResultContract { id: 1, name: "required_authority", behavior: "propagate failure and do not report success", debt_owner: "authority_owner" },
  CleanupResultContract { id: 2, name: "required_durability", behavior: "propagate failure and apply serious-failure latch policy", debt_owner: "durability_coordinator" },
  CleanupResultContract { id: 3, name: "optional_temporary", behavior: "preserve primary result, warn, and record cleanup debt", debt_owner: "owning_task" },
  CleanupResultContract { id: 4, name: "optional_telemetry", behavior: "preserve primary result, warn, and increment visible telemetry debt", debt_owner: "observability_owner" },
];
