pub mod append_writer;
pub mod deletion_record;
pub mod directory_entry;
pub mod entry_header;
pub mod entry_scanner;
pub mod entry_type;
pub mod errors;
pub mod file_header;
pub mod file_record;
pub mod hash_algorithm;
pub mod path_utils;

pub use append_writer::AppendWriter;
pub use deletion_record::DeletionRecord;
pub use directory_entry::{ChildEntry, serialize_child_entries, deserialize_child_entries};
pub use entry_header::{EntryHeader, ENTRY_MAGIC};
pub use entry_scanner::{EntryScanner, ScannedEntry};
pub use entry_type::EntryType;
pub use errors::{EngineError, EngineResult};
pub use file_header::{FileHeader, FILE_HEADER_SIZE, FILE_MAGIC};
pub use file_record::FileRecord;
pub use hash_algorithm::HashAlgorithm;
pub use path_utils::{normalize_path, parent_path, file_name, path_segments};
