//! Writer proof from frozen AIVP fixtures, not production decoder-generated bytes.
use aeordb::engine::v4::dependency::{InvocationPolicyKind, InvocationPolicyV1, decode_invocation_policy, encode_invocation_policy};
use aeordb::engine::v4::reader::MalformedInputClass;

fn policy(kind: InvocationPolicyKind) -> InvocationPolicyV1 {
  let wasm = kind != InvocationPolicyKind::Native;
  InvocationPolicyV1 {
    kind,
    max_request_bytes: if wasm { 8 * 1_024 * 1_024 } else { 0 },
    max_response_bytes: 4 * 1_024 * 1_024,
    max_linear_memory_bytes: if wasm { 64 * 1_024 * 1_024 } else { 0 },
    max_fuel: if wasm { 50_000_000 } else { 0 },
    max_table_elements: if wasm { 100_000 } else { 0 },
    max_structure_nodes: 100_000,
    max_scalar_bytes: 65_536,
    max_structure_depth: 32,
    max_container_members: 65_535,
    max_wasm_instances: u32::from(wasm),
    max_wasm_memories: u32::from(wasm),
    max_wasm_tables: u32::from(wasm),
    max_value_stack_height: 4_096,
    max_recursion_depth: 256,
  }
}

type Limit64 = fn(&mut InvocationPolicyV1) -> &mut u64;
type Limit32 = fn(&mut InvocationPolicyV1) -> &mut u32;

const COMMON64: [(usize, Limit64); 3] = [
  (32, |policy| &mut policy.max_response_bytes),
  (64, |policy| &mut policy.max_structure_nodes),
  (72, |policy| &mut policy.max_scalar_bytes),
];
const COMMON32: [(usize, Limit32); 4] = [
  (80, |policy| &mut policy.max_structure_depth),
  (84, |policy| &mut policy.max_container_members),
  (100, |policy| &mut policy.max_value_stack_height),
  (104, |policy| &mut policy.max_recursion_depth),
];
const WASM64: [(usize, Limit64); 4] = [
  (24, |policy| &mut policy.max_request_bytes),
  (40, |policy| &mut policy.max_linear_memory_bytes),
  (48, |policy| &mut policy.max_fuel),
  (56, |policy| &mut policy.max_table_elements),
];
const WASM32: [(usize, Limit32); 3] =
  [(88, |policy| &mut policy.max_wasm_instances), (92, |policy| &mut policy.max_wasm_memories), (96, |policy| &mut policy.max_wasm_tables)];

#[test]
fn policy_writer_matches_all_six_independent_fixtures() {
  for profile in ["blake3-256", "sha512"] {
    for (kind, name) in [
      (InvocationPolicyKind::Native, "native"),
      (InvocationPolicyKind::PureWasm, "pure-wasm"),
      (InvocationPolicyKind::LegacyWasm, "legacy-wasm"),
    ] {
      let expected =
        std::fs::read(format!("{}/spec/fixtures/v4/invocation-policy-v1/aivp-{profile}-{name}-valid.bin", env!("CARGO_MANIFEST_DIR")))
          .unwrap();
      let input = policy(kind);
      let encoded: [u8; 128] = encode_invocation_policy(&input).unwrap();
      assert_eq!(encoded.as_slice(), expected, "{profile}/{name}");
      assert_eq!(decode_invocation_policy(&encoded).unwrap(), input);
    }
  }
}

#[test]
fn policy_writer_rejects_every_zero_or_unlimited_common_limit_for_each_backend() {
  for kind in [InvocationPolicyKind::Native, InvocationPolicyKind::PureWasm, InvocationPolicyKind::LegacyWasm] {
    for (offset, field) in COMMON64 {
      for invalid in [0, u64::MAX] {
        let mut input = policy(kind);
        *field(&mut input) = invalid;
        assert_eq!(
          encode_invocation_policy(&input).unwrap_err().class(),
          MalformedInputClass::AllocationAmplification,
          "{kind:?}/{offset}"
        );
      }
    }
    for (offset, field) in COMMON32 {
      for invalid in [0, u32::MAX] {
        let mut input = policy(kind);
        *field(&mut input) = invalid;
        assert_eq!(
          encode_invocation_policy(&input).unwrap_err().class(),
          MalformedInputClass::AllocationAmplification,
          "{kind:?}/{offset}"
        );
      }
    }
  }
}

#[test]
fn policy_writer_rejects_each_inapplicable_native_request_or_wasm_limit() {
  for (offset, field) in WASM64 {
    let mut input = policy(InvocationPolicyKind::Native);
    *field(&mut input) = 1;
    assert_eq!(encode_invocation_policy(&input).unwrap_err().class(), MalformedInputClass::CrossRecordClosureMismatch, "{offset}");
  }
  for (offset, field) in WASM32 {
    let mut input = policy(InvocationPolicyKind::Native);
    *field(&mut input) = 1;
    assert_eq!(encode_invocation_policy(&input).unwrap_err().class(), MalformedInputClass::CrossRecordClosureMismatch, "{offset}");
  }
}

#[test]
fn policy_writer_rejects_each_zero_or_unlimited_wasm_limit_in_both_profiles() {
  for kind in [InvocationPolicyKind::PureWasm, InvocationPolicyKind::LegacyWasm] {
    for (offset, field) in WASM64 {
      for invalid in [0, u64::MAX] {
        let mut input = policy(kind);
        *field(&mut input) = invalid;
        assert_eq!(
          encode_invocation_policy(&input).unwrap_err().class(),
          MalformedInputClass::CrossRecordClosureMismatch,
          "{kind:?}/{offset}"
        );
      }
    }
    for (offset, field) in WASM32 {
      for invalid in [0, u32::MAX] {
        let mut input = policy(kind);
        *field(&mut input) = invalid;
        assert_eq!(
          encode_invocation_policy(&input).unwrap_err().class(),
          MalformedInputClass::CrossRecordClosureMismatch,
          "{kind:?}/{offset}"
        );
      }
    }
  }
}

#[test]
fn policy_writer_preserves_wasm32_memory_alignment_and_address_space_boundaries() {
  for kind in [InvocationPolicyKind::PureWasm, InvocationPolicyKind::LegacyWasm] {
    for bytes in [65_536, 1u64 << 32] {
      let mut input = policy(kind);
      input.max_linear_memory_bytes = bytes;
      let encoded = encode_invocation_policy(&input).unwrap();
      assert_eq!(&encoded[40..48], &bytes.to_le_bytes());
    }
    for bytes in [1, 65_535, 65_537, (1u64 << 32) + 65_536] {
      let mut input = policy(kind);
      input.max_linear_memory_bytes = bytes;
      assert_eq!(encode_invocation_policy(&input).unwrap_err().class(), MalformedInputClass::CrossRecordClosureMismatch);
    }
  }
}

#[test]
fn policy_writer_owns_every_resource_field_and_never_emits_reserved_bytes() {
  for kind in [InvocationPolicyKind::Native, InvocationPolicyKind::PureWasm, InvocationPolicyKind::LegacyWasm] {
    let original = policy(kind);
    let baseline = encode_invocation_policy(&original).unwrap();
    let applicable64 = COMMON64.into_iter().chain(WASM64.into_iter().filter(|_| kind != InvocationPolicyKind::Native));
    for (offset, field) in applicable64 {
      let mut input = original.clone();
      let changed = *field(&mut input) + if offset == 40 { 65_536 } else { 1 };
      *field(&mut input) = changed;
      let mut expected = baseline;
      expected[offset..offset + 8].copy_from_slice(&changed.to_le_bytes());
      assert_eq!(encode_invocation_policy(&input).unwrap(), expected, "{kind:?}/{offset}");
    }
    let applicable32 = COMMON32.into_iter().chain(WASM32.into_iter().filter(|_| kind != InvocationPolicyKind::Native));
    for (offset, field) in applicable32 {
      let mut input = original.clone();
      let changed = *field(&mut input) + 1;
      *field(&mut input) = changed;
      let mut expected = baseline;
      expected[offset..offset + 4].copy_from_slice(&changed.to_le_bytes());
      assert_eq!(encode_invocation_policy(&input).unwrap(), expected, "{kind:?}/{offset}");
    }
    assert!(baseline[12..16].iter().chain(&baseline[108..]).all(|byte| *byte == 0));
  }
}
